### ISSUE TITLE
本地没有生成now_data.txt 和lost_data.txt 文件,只能抓取到请求

### ISSUE THREAD

**Issue by Jason1227** [Pactortester/garbevents#17]
本地没有生成now_data.txt 和lost_data.txt 文件,只能抓取到请求

**Comment by Pactortester** [comment]
1. 哪个厂商的埋点？
2. 装证书了吗？
3. URL配置正确了吗？

贴一下代码

**Comment by Jason1227** [comment]
> 1. 哪个厂商的埋点？
> 2. 装证书了吗？
> 3. URL配置正确了吗？
> 
> 贴一下代码

1.神策

**Comment by Jason1227** [comment]
2.已安装
3.正确

**Comment by Jason1227** [comment]
> 1. 哪个厂商的埋点？
> 2. 装证书了吗？
> 3. URL配置正确了吗？
> 
> 贴一下代码

1.神策
2.已安装
3.url正确
![WechatIMG2](https://user-images.githubusercontent.com/13938405/157157546-f5f4a42c-b12e-425c-b856-e91eb06eb03d.jpeg)

**Comment by Pactortester** [comment]
试一下第二种方式

`from garbevents.custom_sensors_events import GetData
from garbevents.settings import Settings as ST

# 埋点上传url 
ST.url = 'http://sensor.wodidashi.com'
# 报告生成路径 
ST.report_path = 'report'
# 所有事件名称 
ST.all_events = ['event_name_1', 'event_name_2']

addons = [
    GetData()
]`

**Comment by Jason1227** [comment]
![WechatIMG3](https://user-images.githubusercontent.com/13938405/157160250-c3081285-370b-45e0-b4a7-6900df7c170f.jpeg)
报了这个错 用的安卓设备

**Comment by Jason1227** [comment]
> 试一下第二种方式
> 
> `from garbevents.custom_sensors_events import GetData from garbevents.settings import Settings as ST
> 
> # 埋点上传url
> ST.url = 'http://sensor.wodidashi.com'
> 
> # 报告生成路径
> ST.report_path = 'report'
> 
> # 所有事件名称
> ST.all_events = ['event_name_1', 'event_name_2']
> 
> addons = [ GetData() ]`

第二种方式也不行

**Comment by Jason1227** [comment]
已解决 谢谢

**Comment by Pactortester** [comment]
> 已解决 谢谢
1. 哪里出错啦？
2. 记得点个star啊！

**Comment by Jason1227** [comment]
> > 已解决 谢谢
> 
> 1. 哪里出错啦？
> 2. 记得点个star啊！
![1646720895623](https://user-images.githubusercontent.com/13938405/157179913-507ce0fe-7e9a-4d4e-8eab-7f119b4b2a32.jpg)
这条指令错了

**Comment by Pactortester** [comment]
记得点个star啊！

**Comment by Jason1227** [comment]
> 记得点个star啊！
好的 
顺便请教下，目前功能只能校验埋点事件是否丢失。能否支持校验事件下的属性值是否丢失或者错误？
