### ISSUE TITLE
神策埋点报错IndexError: list index out of range

### ISSUE THREAD

**Issue by zhuxiumei** [Pactortester/garbevents#2]
拆分后获取API地址====>nyar
Addon error: Traceback (most recent call last):
  File "/Users/a/PycharmProjects/ATo/garb-events/venv/lib/python3.7/site-packages/garbevents/sensors_events.py", line 67, in request
    request_content = str(flow.request.content).split('&')[2].split('=')[1]
IndexError: list index out of range

**Comment by zhuxiumei** [comment]
请问这个 需要你这边解决吗

**Comment by Pactortester** [comment]
你这边的埋点上报url正确么，可以贴出来，让我看看，抓包把链接抓出来！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pactortester/garbevents"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:42
收件人:&nbsp;"Pactortester/garbevents"<garbevents@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Pactortester/garbevents] 神策埋点报错IndexError: list index out of range (#2)





 
请问这个 需要你这边解决吗

**Comment by zhuxiumei** [comment]
url:-------->http://testing-java-api.intranet.atoken.com/nyar/wallet/asset?walletId=14ed6b581e7270c25fdcb9740da9ee0deceea54e9d0c7053878c6006fb97a27f&currencyCode=CNY&app_time_zone=GMT%2B08
拆分后获取API地址====>nyar
Addon error: Traceback (most recent call last):
  File "/Users/a/PycharmProjects/AToken/garb-events/venv/lib/python3.7/site-packages/garbevents/sensors_events.py", line 67, in request
    request_content = str(flow.request.content).split('&')[2].split('=')[1]
IndexError: list index out of range

192.168.115.70:41834: clientconnect

**Comment by Pactortester** [comment]
你这个不是神策的上报url，抓包 找这个 开头的&nbsp;http://sensor.xxx.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pactortester/garbevents"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:49
收件人:&nbsp;"Pactortester/garbevents"<garbevents@noreply.github.com&gt;;
抄送:&nbsp;"李佳玮"<1456470136@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Pactortester/garbevents] 神策埋点报错IndexError: list index out of range (#2)





 
url:--------&gt;http://testing-java-api.intranet.atoken.com/nyar/wallet/asset?walletId=14ed6b581e7270c25fdcb9740da9ee0deceea54e9d0c7053878c6006fb97a27f&amp;currencyCode=CNY&amp;app_time_zone=GMT%2B08
 拆分后获取API地址====&gt;nyar
 Addon error: Traceback (most recent call last):
 File "/Users/a/PycharmProjects/AToken/garb-events/venv/lib/python3.7/site-packages/garbevents/sensors_events.py", line 67, in request
 request_content = str(flow.request.content).split('&amp;')[2].split('=')[1]
 IndexError: list index out of range
 
192.168.115.70:41834: clientconnect

**Comment by zhuxiumei** [comment]
没有抓到这个开头请求的哇，是不是我们没有上传

**Comment by Pactortester** [comment]
问问端上的开发同学，他们知道，请先点个star啊！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pactortester/garbevents"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:02
收件人:&nbsp;"Pactortester/garbevents"<garbevents@noreply.github.com&gt;;
抄送:&nbsp;"李佳玮"<1456470136@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Pactortester/garbevents] 神策埋点报错IndexError: list index out of range (#2)





 
没有抓到这个开头请求的哇，是不是我们没有上传

**Comment by zhuxiumei** [comment]
请求成功了，report的话 是直接生成吗？没看到请求保存数据呢

**Comment by Pactortester** [comment]
看readme.md，你操作 **触发埋点** 会自动保存到report文件夹下

**Comment by zhuxiumei** [comment]
readme.md 文档有些糙啊，么有看到埋点数据哇😂
