### ISSUE TITLE
基于GrowingIO会有更新么？

### ISSUE THREAD

**Issue by meihaoyidian** [Pactortester/garbevents#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pactortester** [comment]
发一下你们的app,我看一下，

**Comment by Pactortester** [comment]
已经适配 请安装最新版 pip install garbevents==2.0.0

https://github.com/Pactortester/garbevents#growingio-demo
