### ISSUE TITLE
神策埋点，没有实现获取埋点功能，且https的链接，报ssl错误

### ISSUE THREAD

**Issue by lsp84ch83** [Pactortester/garbevents#5]
![image](https://user-images.githubusercontent.com/25055457/99640977-9e035400-2a84-11eb-9312-b3d7f196a6ff.png)

**Comment by Pactortester** [comment]
1.https的链接，报ssl错误
答：请确保你的手机已经安装了mitm证书
2.没有实现获取埋点功能
答：请确保 目标url是正确的

**Comment by lsp84ch83** [comment]
> 1.https的链接，报ssl错误
> 答：请确保你的手机已经安装了mitm证书
> 2.没有实现获取埋点功能
> 答：请确保目标url是正确的


> 1.https的链接，报ssl错误
> 答：请确保你的手机已经安装了mitm证书
> 2.没有实现获取埋点功能
> 答：请确保目标url是正确的

您好，已经安装mitm的证书，且上报的url是从开发那里获取的
![image](https://user-images.githubusercontent.com/25055457/99642242-3cdc8000-2a86-11eb-854e-312658588361.png)
方便的话，可以通过QQ或者其它方式，直接联系吗

**Comment by Pactortester** [comment]
先给我点个star,
你可以抓包看一下链接到底对不对

**Comment by lsp84ch83** [comment]
> 先给我点个star,
> 你可以抓包看一下链接到底对不对

抓包是看不到的，貌似是通过日志去上传埋点，比如Android，需要从Android的日志里去查找上传信息

**Comment by Pactortester** [comment]
先给我点个star,你可以抓包看一下链接到底对不对，你加我微信 15624992422




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Pactortester/garbevents"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 下午4:43
收件人:&nbsp;"Pactortester/garbevents"<garbevents@noreply.github.com&gt;;
抄送:&nbsp;"李佳玮"<1456470136@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Pactortester/garbevents] 神策埋点，没有实现获取埋点功能，且https的链接，报ssl错误 (#5)





  
1.https的链接，报ssl错误
 答：请确保你的手机已经安装了mitm证书
 2.没有实现获取埋点功能
 答：请确保目标url是正确的
   
1.https的链接，报ssl错误
 答：请确保你的手机已经安装了mitm证书
 2.没有实现获取埋点功能
 答：请确保目标url是正确的
  
您好，已经安装mitm的证书，且上报的url是从开发那里获取的
 
 方便的话，可以通过QQ或者其它方式，直接联系吗

**Comment by Pactortester** [comment]
pip install garbevents==2.0.0

引擎1：

`# -*- coding: utf-8 -*-

from garbevents.custom_sensors_events import GetData


from garbevents.settings import Settings as ST

'mitmdump -p 8889 -s test_custom_sensors_events.py'

ST.url = 'https://sensors.wenwo.com'
ST.report_path = 'report'
ST.all_events = ['LX_CONVERSATION_MSG_ITEM_FORWAR_CLICK', 'LX_CONVERSATION_SETTING_TOPS_CLICK']

addons = [
    GetData()
]`


引擎2：
`# -*- coding: utf-8 -*-

from garbevents.sensors_events import GetData

from garbevents.settings import Settings as ST

'mitmdump -p 8889 -s test_sensors_events.py'
ST.url = 'http://sensor.wodidashi.com'
ST.report_path = 'report'
ST.all_events = ['LX_CONVERSATION_MSG_ITEM_FORWAR_CLICK', 'LX_CONVERSATION_SETTING_TOPS_CLICK']

addons = [
    GetData()
]
`
