### ISSUE TITLE
神策埋点，win 10 和ipad 11 都无法抓取数据，请问您知道如何解决嘛

### ISSUE THREAD

**Issue by ellezdi0808** [Pactortester/garbevents#6]
![image](https://user-images.githubusercontent.com/21121278/103603888-a20f0680-4f4a-11eb-9815-3fb69ed91ba2.png)
![image](https://user-images.githubusercontent.com/21121278/103603921-b18e4f80-4f4a-11eb-9550-d5db66710cea.png)

**Comment by Pactortester** [comment]
你们是啥app？告诉我，我装一个看下

**Comment by ellezdi0808** [comment]
https://www.xes1v1.com/download.html  
![image](https://user-images.githubusercontent.com/21121278/103624518-9afcee00-4f74-11eb-947a-0d4a29294f47.png)

**Comment by Pactortester** [comment]
好的，我下载看看，明天给你答复

**Comment by ellezdi0808** [comment]
![image](https://user-images.githubusercontent.com/21121278/103721715-55d6cb80-5009-11eb-870c-b0018a4f18a9.png)
您好，昨天是证书的问题已经解决，但是目前抓到的数据，没有加密请求参数的数据显示在终端，同时也没有在本地生成now_data.txt 和lost_data.txt 文件

**Comment by Pactortester** [comment]
github被墙了，我看不到图片 ，加我15624992422

**Comment by Pactortester** [comment]
这是我 抓了下移动端 学而思的app,能正常抓到，如图，有任何疑问再联系我
![image](https://user-images.githubusercontent.com/29191106/103723346-d2b77480-500c-11eb-9b81-e5f666cb9fac.png)

**Comment by Pactortester** [comment]
这是你们学而思 生产 的神策 上报url，捕获到的结果如图；希望多多star,fork，分享一下这个工具！
![image](https://user-images.githubusercontent.com/29191106/103723484-25912c00-500d-11eb-8ec5-b2371da76eaa.png)

**Comment by ellezdi0808** [comment]
您好，您的图片我这里打不开呀，我的本地没有生成now_data.txt 和lost_data.txt 文件

**Comment by Pactortester** [comment]
加我wx15624992422
