### ISSUE TITLE
易观方舟埋点数据加入garbevents 埋点适配计划申请

### ISSUE THREAD

**Issue by zhunan0606** [Pactortester/garbevents#8]
hi，

这里是易观旗下产品——易观Argo的运营同学朱楠，我们在一个开发者社区看到garbevents的埋点适配计划，非常希望可以和garbevents一起合作，加入埋点适配计划，特此申请。

我们看到garbevents的埋点适配计划里包含诸葛IO、神策数据、GrowingIO埋点数据、mixpanel等，易观也在做基于用户行为的分析、运营及画像产品，即易观方舟产品套件，目前客户数量已达500+，并基于产品产出了金融、新零售、汽车、教育等行业解决方案。易观同时积极深耕开发者生态：

- 开源调度产品被纳入Apache孵化器项目——apache dolphinscheduler，目前社区人数已达3000+，

- 开源易观SDK  https://github.com/analysys ，

- 并积极为presto、clickhouse等社区贡献，

- 而为了践行“数据能力平民化”、更于2019年推出了易观方舟产品套件中的用户行为分析产品免费版，取名为Argo， https://github.com/analysys/argo-installer ，因此而荟聚了近2000 Argo 社区爱好者，赋能数百家中小企业搭建用户行为分析系统。

以上陈述皆为表达易观对加入garbevents 埋点适配计划的决心、努力和能力，盼回复。可联系我的邮箱zhunan@analysys.com.cn

**Comment by Pactortester** [comment]
#9 
已适配 易观方舟埋点数据 
试用请查看，https://github.com/Pactortester/garbevents#argo-%E6%98%93%E8%A7%82%E6%96%B9%E8%88%9F-demo
`pip install garbevents==2.0.1`
